name: "Check PRs w Danger JS"
on: [pull_request]

jobs:
  build:
    name: Danger JS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: check
      uses: danger/danger-js@9.1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
